#ifndef __MDADM_ERRORCODE__
#define __MDADM_ERRORCODE__

enum {
	SUCCESS = 0,

	CREATE_RAID_LEVEL_UNSET = 1,
	CREATE_RAID_DEVS_NOT_ENOUGH,
	CREATE_RAID_DEVS_OVER_256,
	CREATE_SPARE_DEVS_NOT_SUPPORT,
	CREATE_LIST_DEVS_MORE_THAN_ARRAY_NEEDED,
	CREATE_BITMAP_NOT_MEANINGFUL,
	CREATE_RAID_LEVEL_UNKNOWN,
	CREATE_GEOMETRY_INVALID,
	CREATE_RAID_DEV_CANNOT_OPEN,
	CREATE_NOT_BLOCK_DEVICE,
	CREATE_UNSUITABLE_STYLE,
	CREATE_TOO_MANY_DEVS,
	CREATE_NO_FREE_SPACE,
	CREATE_FREE_SPACE_SMALL_THAN_GIVEN,
	CREATE_WITHOUT_GIVEN_SIZE_DRIVES,
	CREATE_DEVS_TOO_LARGE,
	CREATE_ABORTED,
	CREATE_MISSING_DEVS_NOT_SUPPORT,
	CREATE_MDDEV_FAIL,
	CREATE_MDDEV_INUSE,
	CREATE_REQUIRE_NEWER_VERSION,
	CREATE_INIT_SUPER_FAIL,
	CREATE_BITMAP_NOT_SUPPORT,
	CREATE_BITMAP_CHUNK_NOT_SUPPORT,
	CREATE_OPEN_CONTAINER_FAIL,
	CREATE_SET_ARRAY_INFO_FAIL,
	CREATE_BITMAP_FAIL,
	CREATE_OPEN_BITMAP_FILE_FAIL,
	CREATE_SET_BITMAP_FILE_FAIL,
	CREATE_ADD_TO_SUPER_FAIL,
	CREATE_ADD_NEW_DISK_FAIL,
	CREATE_FREE_SUPER_TYPE_OBJ_FAIL,
	CREATE_RAID_ACTIVATION_FAIL,
				

	DETAIL_MDDEV_OPEN_FAIL = 101,
	DETAIL_MDDEV_ILLEGAL,
	DETAIL_MDDEV_REQUIRE_NEWER_DRIVER,
	DETAIL_MDDEV_CANNOT_GET_DETAIL,

	MANAGE_STOP_MD_FAIL = 201,
	MANAGE_MD_IN_USE,
	MANAGE_DEVICE_BUSY,
	MANAGE_STOP_CONTAINER_FAIL,

	ASSEMBLE_NO_IDENTITY_INFO = 301
	ASSEMBLE_NEGATIVE_NUM_DEVICES,
	ASSEMBLE_SUPER_INFO_IS_NULL,
	ASSEMBLE_DRIVE_IS_ACTIVE,
	ASSEMBLE_INVALID_MDFD,
	ASSEMBLE_KERNEL_UNSUPPORT,
	ASSEMBLE_MD_ALREADY_ACTIVE,
	ASSEMBLE_CONTAINER_CONTENT_FAIL,
	ASSEMBLE_NEGATIVE_DEV_CNT,
	ASSEMBLE_NO_DEVS_FOR_MD,
	ASSEMBLE_OPEN_DEV_FAIL,
	ASSEMBLE_SUPERBLOCK_DISAPPEARED,
	ASSEMBLE_NO_SUITABLE_DRIVES,
	ASSEMBLE_REWRITE_SUPERBLOCK_FAIL,
	ASSEMBLE_FAIL,						
};

#endif
